name: Auto Tag

on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 確保拉取所有歷史記錄
          fetch-tags: true # 拉取所有標籤

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Get the latest tag
        id: get_latest_tag
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Get the current version
        id: get_version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check if new tag is needed
        id: check_tag
        run: |
          if [ "${{ env.LATEST_TAG }}" == "none" ]; then
            echo "No tags found, creating initial tag"
            echo "NEW_TAG=v${{ env.VERSION }}" >> $GITHUB_ENV
            echo "TAG_NEEDED=true" >> $GITHUB_ENV
          elif [ "v${{ env.VERSION }}" == "${{ env.LATEST_TAG }}" ]; then
            echo "No new tag needed"
            echo "TAG_NEEDED=false" >> $GITHUB_ENV
          else
            echo "New tag needed"
            echo "NEW_TAG=v${{ env.VERSION }}" >> $GITHUB_ENV
            echo "TAG_NEEDED=true" >> $GITHUB_ENV
          fi

      - name: Create new tag
        if: env.TAG_NEEDED == 'true'
        run: |
          git tag ${{ env.NEW_TAG }}
          git push origin ${{ env.NEW_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

