name: check exists tag
on:
  push:
    branches:
      - master

jobs:
  check-latest-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 確保拉取所有歷史記錄
          fetch-tags: true # 拉取所有標籤

      - name: Get the latest tag
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag is ${LATEST_TAG}"
